# https://docs.docker.com/compose/compose-file/
name: foundationx
services:
    api:
        build: .
        env_file: .env
        ports:
            - ${PORTS}
        restart: ${RESTART_POLICY}
        mem_limit: ${HARD_MEMORY_LIMIT}
        mem_reservation: ${SOFT_MEMORY_LIMIT}
