# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push]

jobs:
    build:
        name: Node
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                  version: 8

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install

            - name: Typecheck
              run: pnpm typecheck

            - name: Lint
              run: pnpm lint
